<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>loa</string>
   </array>
  <key>name</key>
  <string>loa</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.loa</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(namespace|import|export|as|class|public|private|var|init|self|is|abstract|let)\b</string>
          <key>name</key>
          <string>keyword.loa</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Z][A-Za-z._]*&apos;*)</string>
          <key>name</key>
          <string>support.type.loa</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-z][A-Za-z._]*&apos;*:)</string>
          <key>name</key>
          <string>entity.name.atom.loa</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-z][A-Za-z._]*&apos;*)</string>
          <key>name</key>
          <string>entity.name.function.loa</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([0-9]+(#[0-9a-zA-Z]+)*)</string>
          <key>name</key>
          <string>constant.numeric.loa</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.loa</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.loa</string>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.loa</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(&apos;(\\.|[^\x{0027}])&apos;)</string>
          <key>name</key>
          <string>string.loa</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//$)</string>
          <key>name</key>
          <string>comment.loa</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(//)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.loa</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(.$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.loa</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\S\s])</string>
          <key>name</key>
          <string>punct.loa</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#todo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\S\s])</string>
          <key>name</key>
          <string>comment.loa</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.loa</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#multi_line_comment__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.loa</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#todo</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#nested_multi_line_comment</string>
        </dict>
       </array>
    </dict>
    <key>nested_multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.loa</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#nested_multi_line_comment__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.loa</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#todo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\S\s])</string>
          <key>name</key>
          <string>comment.loa</string>
        </dict>
       </array>
    </dict>
    <key>nested_multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#nested_multi_line_comment</string>
        </dict>
       </array>
    </dict>
    <key>todo</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(TODO)</string>
          <key>name</key>
          <string>todo.loa</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
